// session
export const SIGN_IN_REQUEST = 'SIGN_IN_REQUEST';
export const SIGN_IN_SUCCESS = 'SIGN_IN_SUCCESS';
export const SIGN_IN_FAILURE = 'SIGN_IN_FAILURE';
export const SIGN_OUT = 'SIGN_OUT';
export const GET_USER_SUCCESS = 'GET_USER_SUCCESS';
export const RESET_SESSION_ERROR = 'RESET_SESSION_ERROR';

// modal
export const CLOSE_MODAL = 'CLOSE_MODAL';
export const OPEN_MODAL = 'OPEN_MODAL';
export const CURRENT_MODAL = 'CURRENT_MODAL';

// tasks
export const GET_TASKS = 'GET_TASKS';
export const CREATED_TASK = 'CREATED_TASK';
export const DELETE_TASK = 'DELETE_TASK';
export const UPDATE_TASK = 'UPDATE_TASK';
export const SET_TASK_TO_EDIT = 'SET_TASK_TO_EDIT';
export const RESET_TASK_TO_EDIT = 'RESET_TASK_TO_EDIT';
export const SET_NOTIFICATIONS = 'SET_NOTIFICATIONS';
export const SET_CURRENT_NOTIFICATION = 'SET_CURRENT_NOTIFICATION';
export const RESET_CURRENT_NOTIFICATION = 'RESET_CURRENT_NOTIFICATION';
